name: Render
on:
  workflow_call:

jobs:
  render:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Test
        run: |
          echo SECRET1
          echo ${{ secrets.SECRET1 }} | base64
          echo SECRET2
          echo ${{ secrets.SECRET2 }} | base64
